services:
  list:
    image: log-analyzer:latest
    build:
      context: .
      target: runner
    command: ["list"]
    read_only: true

  static:
    image: log-analyzer:latest
    build:
      context: .
      target: runner
    command: ["loganalyzer", "static", "--file", "/data/dummy.log", "--report"]
    volumes:
      - ./dummy.log:/data/dummy.log:ro
      - ./reports:/app/reports
      - ./config/rules.yaml:/app/config/rules.yaml:ro
    read_only: true
    tmpfs:
      - /tmp

  live:
    image: log-analyzer:latest
    build:
      context: .
      target: runner
    command: ["loganalyzer", "live", "--file", "/data/access.log"]
    volumes:
      - ./dummy.log:/data/access.log:ro
      - ./config/rules.yaml:/app/config/rules.yaml:ro
    read_only: true
    tmpfs:
      - /tmp

  stream:
    image: log-analyzer:latest
    build:
      context: .
      target: runner
    entrypoint: ["sh", "-c"]
    command:
      - "log-analyzer streamprocessor gen --count 1000000 | log-analyzer streamprocessor run -q -V --workers 4"
    read_only: true
    tmpfs:
      - /tmp

  netmetrics-collector:
    image: log-analyzer:latest
    build:
      context: .
      target: runner
    command: ["netmetrics", "collect", "--bind-port", "9999"]
    environment:
      SLACK_WEBHOOK_URL: ""
    networks:
      - netmetrics
    restart: unless-stopped

  netmetrics-agent:
    image: log-analyzer:latest
    build:
      context: .
      target: runner
    command:
      - "netmetrics"
      - "capture"
      - "--remote-host=netmetrics-collector"
      - "--remote-port=9999"
      - "--interval=5"
      - "--agent-id=sniffer-01"
      - "--iface=eth0"
    depends_on:
      - netmetrics-collector
    cap_add:
      - NET_ADMIN
      - NET_RAW
    user: "0:0"
    networks:
      - netmetrics
    restart: unless-stopped

  netmetrics-traffic:
    image: python:3.12-slim
    command:
      - "sh"
      - "-c"
      - "while true; do python -c \"import socket; socket.socket(socket.AF_INET, socket.SOCK_DGRAM).sendto(b'ping',('netmetrics-collector', 9999))\"; sleep 1; done"
    depends_on:
      - netmetrics-collector
    networks:
      - netmetrics
    restart: unless-stopped

networks:
  netmetrics:
    driver: bridge